version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-ts-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=express_ts_app
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_secret_key
      - JWT_EXPIRES_IN=1d
    networks:
      - app-network
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=express_ts_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local