version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-ts-app-dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=express_ts_app
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=dev_secret
      - JWT_EXPIRES_IN=1d
    networks:
      - app-network
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=express_ts_app
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-dev-data:
    driver: local